### ISSUE TITLE
Please add APK to release section

### ISSUE THREAD

**Issue by rancidfrog** [leorigna/SlimFacebook#3]
Having APK in release section would be greatly appreciated.

**Comment by leorigna** [comment]
I've some problems with the Facebook rules for the name of the app.

**Comment by rancidfrog** [comment]
Problem with Github releases?
https://github.com/leorigna/SlimFacebook/releases

**Comment by leorigna** [comment]
I'm new to github. This is to publish the changelog?

**Comment by rancidfrog** [comment]
No.
In github you can have release APKs and Source in release section:
I.E.
https://github.com/k9mail/k-9/releases
https://github.com/Thunderbottom/UltimateBrowserProject/releases

**Comment by leorigna** [comment]
ah ok thanks. But I would prefer have my app only in the play store to see all the statistics (version of devices, languages)

**Comment by rancidfrog** [comment]
I understand.
But, some people do not have access to playstore.
And, at the moment I do not have access to raccoon by onixbits, https://github.com/onyxbits/Raccoon

**Comment by leorigna** [comment]
Done

**Comment by rancidfrog** [comment]
Thank you
